# Generated by Django 5.1.6 on 2025-02-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('deviceType', models.CharField(choices=[('PHONE', 'Phone'), ('LAPTOP', 'Laptop'), ('TABLET', 'Tablet')], max_length=6)),
                ('year', models.IntegerField()),
                ('size', models.CharField(max_length=40)),
                ('condition', models.CharField(choices=[('BRAND NEW', 'Brand new, never used'), ('GOOD', 'Good condition, minimal usage'), ('AVERAGE USE', 'Used condition, some normal wear and tear'), ('WORN', 'Visible wear and tear, not the best condition'), ('POOR', "Lots of wear and tear which greatly inhibit device's performance"), ('BROKEN', 'Broken and not in working order')], max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=10)),
                ('seller_rating', models.IntegerField()),
                ('accountType', models.CharField(choices=[('REFURB', 'Refurbisher'), ('RECYCLE', 'Recycler')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.device')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sustainability.user')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sustainability.user')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='listing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.user'),
        ),
    ]
